#cmakedefine HAVE_XSCREENSAVER 1
#cmakedefine HAVE_X11 1
#cmakedefine HAVE_XUTIL 1
#cmakedefine HAVE_QCA2 1
#cmakedefine HAVE_KSTATUSNOTIFIERITEM 1
#cmakedefine HAVE_STROPTS_H 1
#cmakedefine HAVE_SYS_ENDIAN_H 1
#cmakedefine HAVE_BYTESWAP_H 1
#cmakedefine HAVE_KIDLETIME 1