#!/bin/bash

# A script for Konversation to call connectToServer for each instance of Konversation.

url=`echo $1 | sed -e "s,irc://,,"`
server_and_port=`echo $url | sed -e "s,\b/.*,,"`
server=`echo $server_and_port| awk -F":" '{print $1}'`
port=`echo $server_and_port| awk -F":" '{print $2}'`
channel_and_password=`echo $url | awk -F"/" '{print $2}'`
channel=`echo $channel_and_password | awk -F"?" '{print $1}'`
password=`echo $channel_and_password | awk -F"?" '{print $2}'`

if test -z "$port";then port=6667;fi;
if test -z "$password";then password="foo";fi;
if test -z "$channel";then channel="#konversation";fi;

if test ! ${channel:0:1} == '#';then channel="#"$channel;fi 

dcop "konversation*" | while read line; do dcop $line Konversation connectToServer $server $port $channel $password; done
