#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
#
# SPDX-FileCopyrightText: 2012 Kristopher Kerwin <kkerwin1@gmail.com>
# SPDX-FileCopyrightText: 2012 Eike Hein <hein@kde.org>

"""
Used to search for a bug at bugs.kde.org.

"""

import subprocess
import sys

try:
    import konversation.dbus
    konversation.dbus.default_message_prefix = 'bug: '

    import konversation.i18n
    konversation.i18n.init()
except ImportError:
    sys.exit("This script is intended to be run from within Konversation.")

try:
    bug = int(sys.argv[3].strip())
except IndexError:
    konversation.dbus.error(i18n("You forgot the bug number."), exit=True)
except ValueError:
    konversation.dbus.error(i18n("Please search by bug number."), exit=True)

try:
    url = 'https://bugs.kde.org/buglist.cgi?quicksearch={0}'.format(bug)
    subprocess.call(['xdg-open', url])
except OSError:
    konversation.dbus.error(i18n("xdg-open not found."), exit=True)
except subprocess.CalledProcessError:
    konversation.dbus.error(i18n("xdg-open failed."), exit=True)

