#!/usr/bin/env perl
# Copyright (C) 2004 by İsmail Dönmez
# Licensed under GPL v2 or later at your option

$SERVER= shift;
$TARGET= shift;

my $i;
my $command;

if( $ARGV[0] eq "yes" ){
    exec 'qdbus', 'org.kde.konversation', '/irc', 'error', 'Requested command is not executed!';
}

foreach $word (@ARGV) {
    $command = $command." ".$word;
}

$ARG_MESSAGE = `exec $command`;

foreach $entry (split(/\n/, $ARG_MESSAGE)) {
    chomp $entry;
    $i=1;
    $entry =~ s/^\//\/\//;
    system 'qdbus', 'org.kde.konversation', '/irc', 'say', $SERVER, $TARGET, $entry;
}

unless($i) {
    exec 'qdbus', 'org.kde.konversation', '/irc', 'error', "Command @ARGV doesn't exist";
}
