#!/usr/bin/env perl
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# SPDX-FileCopyrightText: 2004 İsmail Dönmez <ismail@kde.org>

$SERVER = shift;
$TARGET = shift;

sub RANDOM_INT ($$) {
    my($min, $max) = @_;
    return $min if $min == $max;
    ($min, $max) = ($max, $min)  if  $min > $max;
    return $min + int rand(1 + $max - $min);
}

open(FORTUNES,"fortunes.dat") or die("Could not open fortunes file!");

while (<FORTUNES>) {
    chomp;
    ++$TOTAL_LINES;
}

seek(FORTUNES,0,0);

srand;
$LINE = RANDOM_INT(0,$TOTAL_LINES - 5);

$MESSAGE = "4Random Fortune: ";

while (<FORTUNES>) {
    $LINE_COUNT++;

    if ( !$START && $LINE_COUNT >= $LINE ) {
	if ( $_ eq "\%\n" ) {
	    $START = 1;
	    next;
	}
	    next;
    }
    
    elsif ( $START ) {
	if( $_ eq "\%\n" ) {
	    last;
	}
	else {
	    chomp;
	    s/(\s)+/$1/g;
	    $MESSAGE .= $_." ";
	}
    }
}
close(FORTUNES);
my $dbus_cmd = $ENV{'KONVERSATION_DBUS_BIN'} || 'qdbus';
exec $dbus_cmd, 'org.kde.konversation', '/irc', 'say', $SERVER, $TARGET, $MESSAGE;
