#!/usr/bin/env bash
#
# Creates a TinyURL from a long URL
# Licensed under GPL v2 or later at your option
# Copyright 2007 Terence Simpson

SERVER=$1
TARGET=$2
export URL="$3"
NICK="$4"

if test ! -z $URL; then
  if test $(which curl); then
    TINYURL="$(curl -s -i http://tinyurl.com/create.php?url=$URL|grep "The following URL" -A4|tail -1|awk -F\> '{print $3}'|sed 's,</b,,')"
  else
    TINYURL="$(wget -T10 -t2 -qO- http://tinyurl.com/create.php?url=$URL|grep "The following URL" -A4|tail -1|awk -F\> '{print $3}'|sed 's,</b,,')"
  fi
else qdbus org.kde.konversation /irc error "No url given: usage is \"/tinyurl URL [NickName]\""
    exit 1
fi

if test -z $TINYURL; then
    qdbus $PORT org.kde.konversation /irc error "Unable run tinyurl script, please make sure you have curl or wget installed"
else
    if test ! -z $NICK; then
        qdbus $PORT org.kde.konversation /irc say $SERVER "$TARGET" "${NICK}: $TINYURL"
    else
        qdbus $PORT org.kde.konversation /irc say $SERVER "$TARGET" "$TINYURL"
    fi
fi
