#!/bin/bash

PORT=$1
SERVER=$2
TARGET=$3

if [ ! `dcop amarok` ];
then
  dcop $PORT Konversation error "Amarok not running."
  exit;
fi

if [ ! $TARGET ]
then
  dcop $PORT Konversation error "Can't write into status view."
else
  PLAYING=`dcop amarok player isPlaying`
  
  if [ "$PLAYING" = "false" ]
  then
    dcop $PORT Konversation error "Nothing's playing in Amarok."
  else  
    TEXT=`dcop amarok player nowPlaying`

    if [ ! $TEXT ]
    then
	dcop $PORT Konversation error "Nothing's playing in Amarok."
    else
	dcop $PORT Konversation say $SERVER "$TARGET" "/me plays $TEXT"
    fi
  fi
fi
