#!/bin/sh

PORT=$1
SERVER=$2
TARGET=$3
BUG=$4

if [ ! $TARGET ]
then
  dcop $PORT default error "Can't write into status view."
else
  if [ -z $BUG ]
  then
    dcop $PORT default error "You forgot the bug number!"
  else
    kfmclient openURL http://bugs.kde.org/show_bug.cgi?id=$4
  fi
fi
