#!/usr/bin/env perl
# Copyright (C) 2004 by İsmail Dönmez
# Licensed under GPL v2 or later at your option

$PORT= shift;
$SERVER= shift;
$TARGET= shift;

if( $ARGV[0] eq "yes" ){
    exec ("dcop $PORT Konversation error \"Requested command is not executed!\" ");
}

$ARG_MESSAGE = `@ARGV`;

foreach $entry (split(/\n/, $ARG_MESSAGE)) {
    chomp $entry;
    $entry =~ s/^\//\/\//;
    unless($i) { 
	system("dcop $PORT Konversation say $SERVER \"$TARGET\" \"Output Of Command : %B @ARGV %B\" ");
	$i=1;
    }
    system ("dcop $PORT Konversation say $SERVER \"$TARGET\" \"$entry\" ");
}

unless($i) {
    exec("dcop $PORT Konversation error \"Command @ARGV doesn't exist\!\"");
}
