#!/usr/bin/env perl

use warnings;
use strict;

my $PORT= shift;
my $SERVER= shift;
my $TARGET= shift;

my $message;
my $random;
my $input;
my @chars;
my $i = 0;

if(!@ARGV){
    exec ("dcop $PORT Konversation error \"Colorizer script needs a message argument!\" ");
}

foreach (@ARGV) {
    if($i == 0) {
	$input = $_;
	$i = 1;
    }
    else {
	$input = $input." ".$_;
    }
}

if( utf8::valid($input) ) {
    utf8::decode($input);
}

@chars = split //, $input;

srand(time());

foreach (@chars) {
  $random = int(rand(15))+1;
  $message = $message."%C".$random.$_;
}

system ("dcop $PORT Konversation say $SERVER \"$TARGET\" \"$message\" ");

