#!/usr/bin/env perl
# Copyright (C) 2004 by İsmail Dönmez
# Licensed under GPL v2 or later at your option

use warnings;
use strict;

my $PORT= shift;
my $SERVER= shift;
my $TARGET= shift;

my $message;
my $random;
my $input;
my @chars;
my $i = 0;

if(!@ARGV){
    exec ("dcop $PORT Konversation error \"Colorizer script needs a message argument!\" ");
}

$input = join " ", @ARGV;

if( utf8::valid($input) ) {
    utf8::decode($input);
}

@chars = split //, $input;

$message = "";

foreach (@chars) {
  # Rainbow colors. Code courtesy of boren
  $i = ($i+1)%16;
  $i++ if $i == 1;
  $message = $message."%C".$i.$_;
}

system ("dcop $PORT Konversation say $SERVER \"$TARGET\" \"$message\" ");

