#!/usr/bin/env perl

# Insult script for Konversation
# made by John Tapsell (john.tapsell@kdemailnet)


$PORT = shift;
$SERVER = shift;
$TARGET = shift;

$USER = shift;

@a = qw( artless bawdy beslubbering bootless churlish cockered clouted
craven currish dankish dissembling droning errant fawning fobbing
froward frothy gleeking goatish gorbellied impertinent infectious
jarring loggerheaded lumpish mammering mangled mewling paunchy pribbling
puking puny qualling rank reeky roguish ruttish saucy spleeny spongy
surly tottering unmuzzled vain venomed villainous warped wayward weedy
yeasty );

@b = qw( base-court bat-fowling beef-witted beetle-headed boil-brained
clapper-clawed clay-brained common-kissing crook-pated dismal-dreaming
dizzy-eyed doghearted dread-bolted earth-vexing elf-skinned fat-kidneyed
fen-sucked flap-mouthed fly-bitten folly-fallen fool-born full-gorged
guts-griping half-faced hasty-witted hedge-born hell-hated idle-headed
ill-breeding ill-nurtured knotty-pated milk-livered motley-minded
onion-eyed plume-plucked pottle-deep pox-marked reeling-ripe rough-hewn
rude-growing rump-fed shard-borne sheep-biting spur-galled swag-bellied
tardy-gaited tickle-brained toad-spotted unchin-snouted weather-bitten
);

@c = qw( apple-john baggage barnacle bladder boar-pig bugbear bum-bailey
canker-blossom clack-dish clotpole coxcomb codpiece death-token dewberry
flap-dragon flax-wench flirt-gill foot-licker fustilarian giglet gudgeon
haggard harpy hedge-pig horn-beast hugger-mugger joithead lewdster lout
maggot-pie malt-worm mammet measle minnow miscreant moldwarp mumble-news
nut-hook pigeon-egg pignut puttock pumpion ratsbane scut skainsmate
strumpet varlet vassal whey-face wagtail );

if( $USER eq "" ) {
  @INSULT=("You are a", $a[int(rand($#a))], 
          $b[int(rand($#b))], $c[int(rand($#c))]);
} else {
  @INSULT=($USER, "is a", $a[int(rand($#a))],
          $b[int(rand($#b))], $c[int(rand($#c))]);
}

exec 'dcop', $PORT, 'Konversation', 'say', $SERVER, $TARGET, join(" ", @INSULT);


