#!/bin/bash

#
# Licensed under GPL v2 or later at your option
# Copyright 2005 by John Tapsell <john.tapsell@kdemail.net>

PORT=$1;
SERVER=$2;
TARGET=$3;

FOLDER=$4;


if [ "$FOLDER" = "" ] ; then
  FOLDER="inbox"
fi


getmails()
{

  dcop kmail > /dev/null || {
    dcop $PORT Konversation info "Sorry kmail is not running"
    exit
  }

  for f in $(dcop kmail KMailIface folderList) ; do
   MAILFOLDER=$(dcop $(dcop kmail KMailIface getFolder $f) "displayPath" | grep -i $FOLDER)
   if [ "$MAILFOLDER" != "" ] ; then
   
     MAILCOUNT=$(dcop $(dcop kmail KMailIface getFolder $f ) "unreadMessages()" )
     MAILTOTALCOUNT=$(dcop $(dcop kmail KMailIface getFolder $f ) "messages()" )
     if [ "$MAILCOUNT" = "" ] ; then MAILCOUNT = "0" ; fi
     if [ "$MAILCOUNT" != 0 ] ;  then
       echo "Email folder %C2$MAILFOLDER%C1 has %C2$MAILCOUNT%C1 unread messages, out of %C2$MAILTOTALCOUNT%C1"
     fi
   fi
  done

}

getmails | while read line; do dcop $PORT Konversation say $SERVER "$TARGET" "$line"; done

