#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright 2005 İsmail Dönmez (Resistence is futile, turn on unicode!)
# Licensed under GPLv2 or later at your option
#
# One media command to rule them all, inspired from Kopete's now listening plugin

import os
import sys
from subprocess import *

global port;
global server;
global target;

def check_running(application):
    running = Popen(["dcop", application], stdout=PIPE).communicate()[0]
    
    if running:
        return 1
    else:
        return 0

def pretty_print(title, artist, album):
    title.decode('utf-8')
    artist.decode('utf-8')
    album.decode('utf-8')

    encoding = Popen(["dcop", port, 'Konversation', 'getChannelEncoding', server, target], stdout=PIPE).communicate()[0]
    lang = os.environ.get("LANG")
    lcall = os.environ.get("LC_ALL")

    if (artist and album ) and (artist != album):
        return "/me is listening to \"%s\" by %s on %s"%(title,artist,album)
    elif artist:
	return "/me is listening to \"%s\" by %s"%(title,artist)
    elif album:
	return "/me is listening to \"%s\" on %s"%(title,album)
    else:
	return "/me is listening to \"%s\" "%(title)


if __name__ == "__main__":

    port = sys.argv[1]
    server = sys.argv[2]
    target = sys.argv[3]
    
    bad_apps = None;

    amarok = check_running('amarok')
    juk = check_running('juk')
    kaffeine = check_running('kaffeine')
    noatun = check_running('noatun')

    if amarok:
        title = os.popen('dcop amarok player title').readline().rstrip('\n')
        artist = os.popen('dcop amarok player artist').readline().rstrip('\n')
        album = os.popen('dcop amarok player album').readline().rstrip('\n')

        if title:
            string = pretty_print(title,artist,album)+' [amaroK]'
            Popen(['dcop', port, 'Konversation', 'say', server, target, string]).communicate()
            sys.exit(0)
        else:
            bad_apps = ['amaroK']

    if juk:
        title = os.popen('dcop juk Player trackProperty Title').readline().rstrip('\n')
        artist = os.popen('dcop juk Player trackProperty Artist').readline().rstrip('\n')
        album = os.popen('dcop juk Player trackProperty Album').readline().rstrip('\n')

        if title:
            string = pretty_print(title,artist,album)+' [JuK]';
            Popen(['dcop', port, 'Konversation', 'say', server, target, string]).communicate()
            sys.exit(0)
        else:
            if error:
                bad_apps.append('JuK')
            else:
                bad.apps = ['JuK']

    if kaffeine:
        string = os.popen('dcop kaffeine KaffeineIface title').readline().rstrip('\n')
    
        if string:
            string.decode('utf-8')
            Popen(['dcop', port, 'Konversation', 'say', server, target, '"/me is playing', string,' [Kaffeine]\"']).communicate()
            sys.exit(0)
        else:
            if error:
                bad_apps.append('Kaffeine')
            else:
                bad_apps = ['Kaffeine']

    if noatun:
        string = popen('dcop noatun Noatun title').readline().rstrip('\n');

        if string:
            string.decode('utf-8')
            Popen(['dcop', port, 'Konversation', 'say', server, target, '"/me is playing', string, ' [Noatun]"']).communicate();
            sys.exit(0)
        else:
            if error:
                bad_apps.append('Noatun')
            else:
                bad_apps = ['Noatun']


    if not amarok and not juk and not kaffeine and not noatun:
	os.popen("dcop %s Konversation error \"No supported media player is running\""%(port))

    if bad_apps and bad_apps.__len__:
        error = ','.join(bad_apps)
        print "Error is %s"%(error)
	os.popen("dcop %s Konversation error \"Nothing is playing in %s\""%(port,error))
        sys.exit(1)

