#!/usr/bin/env bash
#
# Licensed under GPL v2 or later
# Copyright 2007 Terence Simpson

PORT=$1
SERVER=$2
TARGET=$3
export URL="$4"

if test ! -z $URL; then
    TINYURL="$(curl -s -i http://tinyurl.com/create.php?url=$URL|grep "The following URL" -A3|tail -1|awk -F\> '{print $3}'|sed 's,</b,,')"

    if test -z $TINYURL; then
        dcop $PORT default error "Unable run tinyurl script, please make sure you have curl installed"
    else
        dcop $PORT default say $SERVER "$TARGET" "$TINYURL"
    fi
fi

