#!/usr/bin/perl -w

$PORT = shift;
$SERVER = shift;
$TARGET = shift;
$OPTION = shift;

@stations = `dcop KWeatherService WeatherService listStations`;

if( ! @stations ) {
  exec ("dcop $PORT Konversation say $SERVER \"$TARGET\" \"KWeather is not installed or not running!\" ");
} 

if( $OPTION && $stations[$OPTION-1] ) {
  @stations = $stations[$OPTION-1];
}

foreach $station (@stations) {

  $city = `dcop KWeatherService WeatherService stationName $station`;
  $temperature = `dcop KWeatherService WeatherService temperature $station`;
  $pressure = `dcop KWeatherService WeatherService pressure $station`; 
  $wind = `dcop KWeatherService WeatherService wind $station`;
  $detail = `dcop KWeatherService WeatherService weather $station`;

  # Fix details
  
  $i = 0;
  chomp $detail;
  
  foreach $det (split(/\n/,$detail)) {
    chomp $det;
    if( $i==0 ) {
      $details = $det;
      $i = 1;
    }
    else {
      $details = $details.", ".$det;
    }
  }
  
  $pressure =~ s/\"/\\\"/g; # Escape double quote

  chomp $city;
  chomp $temperature;
  chomp $pressure;
  chomp $wind;


  if( $detail =~ /(\S)+/ ) {
  $MESSAGE = "Current Weather for %B$city%B : %B$details%B, Temperature: %B$temperature%B, Pressure: %B$pressure%B, Wind: %B$wind%B";
  }
  else {
  $MESSAGE = "Current Weather for %B$city%B : Temperature: %B$temperature%B, Pressure: %B$pressure%B, Wind: %B$wind%B";
  }
  
  system ("dcop $PORT Konversation say $SERVER \"$TARGET\" \"$MESSAGE\" ");

}
